export const siteConfig = {
  name: "Payment Transfer System",
  nameAr: "نظام إدارة الحوالات المالية",
  tagline: "منصة Full-Stack لإدارة الحوالات المالية متعددة الفروع",
  description:
    "نظام إدارة حوالات مالية متكامل — ثلاثة أدوار، تقارير PDF/Excel، إشعارات فورية، ولوحات تحكم احترافية.",
  author: "Ahmad Al-Halwany",
  github: "https://github.com/ahmad-alhalwany/payment-transfer-system",
  url: "https://payment-transfer-system.vercel.app",
  demoPassword: "demo123",
  demoAccounts: [
    {
      role: "director",
      roleAr: "مدير عام",
      username: "director",
      password: "demo123",
      dashboard: "/dashboard/director",
      color: "from-violet-500 to-purple-600",
      icon: "👔",
    },
    {
      role: "branch_manager",
      roleAr: "مدير فرع",
      username: "manager",
      password: "demo123",
      dashboard: "/branch-dashboard",
      color: "from-blue-500 to-cyan-600",
      icon: "🏢",
    },
    {
      role: "employee",
      roleAr: "موظف",
      username: "employee",
      password: "demo123",
      dashboard: "/money-transfer",
      color: "from-emerald-500 to-teal-600",
      icon: "💼",
    },
  ],
  features: [
    {
      title: "حوالات متعددة العملات",
      description: "إرسال واستقبال الحوالات بين الفروع بـ SYP و USD مع تتبع كامل لكل عملية.",
      icon: "💸",
    },
    {
      title: "ثلاثة أدوار مستخدمين",
      description: "لوحات تحكم مخصصة للمدير العام ومدير الفرع والموظف مع صلاحيات دقيقة.",
      icon: "👥",
    },
    {
      title: "تقارير وتحليلات",
      description: "تقارير قابلة للتصفية مع تصدير PDF و Excel ورسوم بيانية تفاعلية.",
      icon: "📊",
    },
    {
      title: "إيصالات PDF عربية",
      description: "طباعة إيصالات حوالات منسّقة بالعربية مع تحويل المبلغ إلى كلمات.",
      icon: "🧾",
    },
    {
      title: "إشعارات فورية",
      description: "تنبيهات لحظية عبر Socket.io عند وصول حوالات جديدة أو تغيير الحالة.",
      icon: "🔔",
    },
    {
      title: "إدارة الفروع والأموال",
      description: "تخصيص الأموال، تتبع الأرباح، الضرائب، والمخزون على مستوى كل فرع.",
      icon: "🏦",
    },
  ],
  techStack: [
    { name: "Next.js 14", category: "frontend" },
    { name: "React 18", category: "frontend" },
    { name: "TypeScript", category: "frontend" },
    { name: "Tailwind CSS", category: "frontend" },
    { name: "FastAPI", category: "backend" },
    { name: "PostgreSQL", category: "backend" },
    { name: "SQLAlchemy", category: "backend" },
    { name: "JWT Auth", category: "backend" },
    { name: "Socket.io", category: "realtime" },
    { name: "Recharts", category: "frontend" },
    { name: "jsPDF", category: "frontend" },
  ],
  stats: [
    { value: "3", label: "أدوار مستخدمين" },
    { value: "25+", label: "صفحة وواجهة" },
    { value: "2", label: "عملات مدعومة" },
    { value: "100%", label: "عربي RTL" },
  ],
} as const;
